tenttiarkisto/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'exams.views.frontpage'),
    # url(r'^tenttiarkisto/', include('tenttiarkisto.foo.urls')),
    url(r'^courses/$', 'exams.views.courselist'),
    url(r'^courses/add/$', 'exams.views.addcourse'),
    url(r'^courses/(?P<course_id>\d+)/(.+)?$', 'exams.views.courseview'),
    url(r'^exams/(?P<exam_id>\d+)/(.+)?/delete$', 'exams.views.delete_exam'),
    url(r'^exams/(?P<exam_id>\d+)/(.+)?/edit$', 'exams.views.edit_exam'),
    url(r'^exams/(?P<exam_id>\d+)/(.+)?$', 'exams.views.examview'),
    url(r'^exams/add/$', 'exams.views.addexam'),
    url(r'^examfile/(?P<examfile_id>\d+)/delete$', 'exams.views.delete_examfile'),

    # account stuff
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'account/login.html'}),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^register/$', 'exams.views.register'),
    url(r'^account/$', 'exams.views.modifyaccount'),
    url(r'^ownexams/$', 'exams.views.accountexams'),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

# serve uploaded files in dev
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

exams/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from exams.utils import ExtFileField
from django.conf import settings
from os import path

class Course(models.Model):
  code = models.CharField(max_length = 20, unique = True)
  name = models.CharField(max_length = 100)
  def get_absolute_url(self):
    return "/courses/%i/%s/" % (self.id, slugify(self.name))
  def __unicode__(self):
    return "%s: %s" % (self.code, self.name)

class Lang(models.Model):
  code = models.CharField(max_length = 3)
  name = models.CharField(max_length = 20)
  def __unicode__(self):
    return self.name

class Exam(models.Model):
  course = models.ForeignKey(Course)
  desc = models.CharField(max_length = 100, help_text = "e.g. \"second midterm\"")
  exam_date = models.DateField(help_text = "Please use the following format: YYYY-MM-DD.")
  date_added = models.DateField(auto_now_add = True)
  lang = models.ForeignKey(Lang)
  submitter = models.ForeignKey(User, null = True, blank = True)
  def get_absolute_url(self):
    return "/exams/%i/%s/%s/" % (self.id, slugify(self.course.name), slugify(self.exam_date))
  def __unicode__(self):
    return "%s: %s %s" % (self.course.code, self.exam_date, self.desc)

def exam_file_name(instance, filename):
  return '/'.join(['exams',  ''.join([str(instance.exam.id), path.splitext(filename)[1]])])

class ExamFile(models.Model):
  exam = models.ForeignKey(Exam)
  exam_file = ExtFileField(upload_to = exam_file_name, ext_whitelist = settings.TENTTIARKISTO_FILE_EXTENSIONS)

# maintainers for frontpage

class Maintainer(models.Model):
  group = models.CharField(max_length = 100)
  email = models.EmailField()

  def view_email(self):
    return self.email.replace("@", " (at) ")

exams/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db.models import Count, Q
from django.template import RequestContext
from exams.models import Course, Exam, ExamFile, Maintainer
from django.forms import EmailField, ModelForm, Form, PasswordInput, CharField
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect, HttpResponseNotAllowed, HttpResponseForbidden
from datetime import datetime

def frontpage(request):
  maintainers = Maintainer.objects.order_by('group').all()
  return render_to_response('index.html', {'maintainers': maintainers}, context_instance=RequestContext(request))

def courselist(request):
  q = request.GET.get('q', '').strip()
  all_courses = Course.objects.annotate(exam_count=Count('exam')).order_by('code').filter(Q(name__icontains=q)|Q(code__icontains=q)).all()
  return render_to_response('course/courselist.html', {'courses': all_courses}, context_instance=RequestContext(request))

def courseview(request, course_id):
  course = get_object_or_404(Course, pk=course_id)
  return render_to_response('course/courseview.html', {'course': course, 'exams': course.exam_set.order_by('-exam_date').all()}, context_instance=RequestContext(request))

class CourseForm(ModelForm):
  class Meta:
    model = Course

def addcourse(request):
  saved = False
  course = None
  if request.method == 'POST':
    form = CourseForm(request.POST)
    if form.is_valid():
      course = form.save()
      saved = True
      form = CourseForm()
  else:
    form = CourseForm()
  return render_to_response('course/addcourse.html', {'form': form, 'saved': saved, 'course': course}, context_instance=RequestContext(request))

# exam & add exam views

class ExamForm(ModelForm):
  class Meta:
    model = Exam
    exclude = ('submitter',)

class ExamFileForm(ModelForm):
  class Meta:
    model = ExamFile
    exclude = ('exam',)

def allowed_to_edit_exam(exam, user):
  return exam.submitter == user

def examview(request, exam_id):
  exam = get_object_or_404(Exam, pk=exam_id)
  fileform = ExamFileForm()
  added = False
  if request.method == 'POST':
    fileform = ExamFileForm(request.POST, request.FILES)
    if fileform.is_valid():
      examfile = fileform.save(commit = False)
      examfile.exam = exam
      examfile.save()
      fileform = ExamFileForm()
      added = True
  return render_to_response('exam/examview.html', {'exam': exam, 'files': exam.examfile_set.all(), 'fileform': fileform, 'added': added, 'allowed_to_edit_exam': allowed_to_edit_exam(exam, request.user)}, context_instance=RequestContext(request))

def delete_exam(request, exam_id):
  if request.method == 'POST':
    exam = get_object_or_404(Exam, pk=exam_id)
    if allowed_to_edit_exam(exam, request.user):
      exam.delete()
      return HttpResponseRedirect(exam.course.get_absolute_url())
    else:
      return HttpResponseForbidden("403 Forbidden")
  else:
    return HttpResponseNotAllowed("405 Method not allowed")

def delete_examfile(request, examfile_id):
  if request.method == 'POST':
    examfile = get_object_or_404(ExamFile, pk=examfile_id)
    if allowed_to_edit_exam(examfile.exam, request.user):
      examfile.delete()
      return HttpResponseRedirect(examfile.exam.get_absolute_url())
    else:
      return HttpResponseForbidden("403 Forbidden")
  else:
    return HttpResponseNotAllowed("405 Method not allowed")

def edit_exam(request, exam_id):
  exam = get_object_or_404(Exam, pk=exam_id)
  if not allowed_to_edit_exam(exam, request.user):
    return HttpResponseForbidden("403 Forbidden")
  form = ExamForm(instance=exam)
  if request.method == 'POST':
    form = ExamForm(request.POST, instance=exam)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect(exam.get_absolute_url())
  return render_to_response('exam/editexam.html', {'form': form}, context_instance=RequestContext(request))

def addexam(request):
  added = False
  exam = None
  form = ExamForm(initial = {"exam_date": datetime.now().strftime("%Y-%m-%d")})
  fileform = ExamFileForm()
  if request.method == 'POST':
    form = ExamForm(request.POST)
    fileform = ExamFileForm(request.POST, request.FILES)
    if form.is_valid() and fileform.is_valid():
      exam = form.save(commit = False)
      if request.user.is_authenticated():
        exam.submitter = request.user
      exam.save()
      examfile = fileform.save(commit = False)
      examfile.exam = exam
      examfile.save()
      fileform = ExamFileForm()
      form = ExamForm()
      added = True
  # sort the courses properly
  form.fields["course"].queryset = Course.objects.order_by('code').all()
  return render_to_response('exam/addexam.html', {'form': form, 'added': added, 'fileform': fileform, 'new_exam': exam}, context_instance=RequestContext(request))


# user registration view

# a user creation form that requires email
class UserCreationEmailForm(UserCreationForm):
  email = EmailField(required=True, help_text = "We will only use email to help you recover your account.")
  class Meta:
    model = User
    fields = ("username", "email", "password1", "password2")
  def save(self, commit=True):
    user = super(UserCreationEmailForm, self).save(commit=False)
    user.email = self.cleaned_data["email"]
    if commit:
      user.save()
    return user

def register(request):
  if request.user.is_authenticated():
    return HttpResponseRedirect('/')

  created = False
  if request.method == 'POST':
    form = UserCreationEmailForm(request.POST)
    if form.is_valid():
      created = True
      form.save()
      # a hack (?) to log the user in after registering
      user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
      login(request, user)
  else:
    form = UserCreationEmailForm()
  return render_to_response('account/register.html', {'form': form, 'created': created}, context_instance=RequestContext(request))

# view for changing account details

class ModifyAccountForm(Form):
  current_password = CharField(widget = PasswordInput)
  email = EmailField()
  new_password1 = CharField(label = "New password", help_text = "Optional", widget = PasswordInput, required = False)
  new_password2 = CharField(label = "New password confirmation", help_text = "Enter the same password as above, for verification if you want to change your password.", widget = PasswordInput, required = False)

  def clean(self):
    cleaned_data = super(ModifyAccountForm, self).clean()
    new_pw1 = cleaned_data.get('new_password1')
    new_pw2 = cleaned_data.get('new_password2')
    if new_pw1 != new_pw2:
      del cleaned_data['new_password1']
      del cleaned_data['new_password2']
      self._errors['new_password2'] = self.error_class(["The two password fields didn't match."])

    return cleaned_data

@login_required
def modifyaccount(request):
  form = ModifyAccountForm(initial = {"email": request.user.email})
  saved = False
  if request.method == "POST":
    form = ModifyAccountForm(request.POST)
    if form.is_valid():
      auth_user = authenticate(username = request.user.username, password = form.cleaned_data['current_password'])
      if auth_user is not None:
        # form valid, password correct, save the data
        if form.cleaned_data['new_password1'] != '':
          auth_user.set_password(form.cleaned_data['new_password1'])
          new_pw = True
        auth_user.email = form.cleaned_data['email']
        saved = True
        auth_user.save()
      else:
        form._errors['current_password'] = form.error_class(["The password was wrong!"])
  return render_to_response('account/modifyaccount.html', {"form": form, 'saved': saved}, context_instance=RequestContext(request))

# view for exams added by current user
@login_required
def accountexams(request):
  exams = Exam.objects.filter(submitter = request.user).order_by("-date_added")
  return render_to_response('account/ownexams.html', {"exams": exams}, context_instance=RequestContext(request))

templates/addcourse.html
{% extends "base.html" %}

{% block content %}
<h2>Add a course</h2>
{% if saved %}
<div class="alert alert-success">
  The course was succesfully added! <a href="{{ course.get_absolute_url }}">View the course page</a>
</div>
{% endif %}
<form action="/courses/add/" class="well" method="post">{% csrf_token %}
{% include "genericform.html" %}
<input type="submit" value="Add course" class="btn" />
</form>
{% endblock %}

templates/addexam.html
{% extends "base.html" %}

{% block js %}
  $(function () {
    $("#id_exam_date").datepicker({
      format: "yyyy-mm-dd",
      weekStart: 1
    });

    // replace the simple select with something more useful for course selection
    $("#id_course").hide();
    // construct an array of entries for typeahead
    entries = [];
    // keep track of full course code & name -> id
    mapping = {};
    $("#id_course option[value!='']").each(function (i, e) {
      entries.push(e.innerHTML);
      mapping[e.innerHTML] = $(e).attr("value");
    });

    // insert a textbox for course
    $("#id_course").after('<input type="text" id="course_typeahead">');
    // make the textbox reflect the select state if not empty
    if ($("#id_course option[selected]").attr("value") != "") {
      $("#course_typeahead").val($("#id_course option[selected]")[0].innerHTML);
    }

    $("#course_typeahead").typeahead({
      source: entries
    }); 

    // make course changes update the hidden selectbox too
    $("#course_typeahead").change(function () {
      text = $("#course_typeahead").val(); 
      if (typeof mapping[text] != "undefined") {
        $("#id_course").val(mapping[text]);
      } else {
        $("#id_course").val("");
      }
    });
  });
{% endblock %}

{% block content %}
<h2>Add an exam</h2>
{% if added %}
<div class="alert alert-success">
  The exam was succesfully added! <a href="{{ new_exam.get_absolute_url }}">View the exam page</a>
</div>
{% endif %}
<form action="/exams/add/" method="post" class="well" enctype="multipart/form-data">{% csrf_token %}
{% include "genericform.html" %}
{% include "genericform.html" with form=fileform %}
<input type="submit" value="Add exam" class="btn" />
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/datepicker.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/select2.css" />
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/select2.min.js"></script>
    <title>{% block title %}Tenttiarkisto{% endblock %}</title>
    <script type="text/javascript">
      $(function(){
        // hide fallback tooltips and construct javascript ones
        $(".form_helptext").hide().each(function(i, e) {
          $("#" + $(e).attr("data-field-id")).tooltip({title: e.innerHTML.replace(/^ *\((.+)\)$/, "$1")});
        });
        // add delete confirmations
        $(".confirm-delete").click(function(e) {
          return window.confirm("Are you sure you want to delete?");
        });
      });
      {% block js %}{% endblock %}
    </script>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-705708-2']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="span12 well"><h1>Tenttiarkisto slogan here!</h1></div>
    </div>
    <div class="row-fluid">
      <div class="span2 well">
        {% block sidebar %}
        <ul class="nav nav-list">
            <li class="nav-header">Browse</li>
            <li><a href="/">Front page</a></li>
            <li><a href="/courses/">All courses</a></li>
            <li class="nav-header">Add</li>
            <li><a href="/courses/add/">Add a course</a></li>
            <li><a href="/exams/add/">Add an exam</a></li>
            {% if user.is_authenticated %}
              <li class="nav-header">Logged in as {{ user.username }}</li>
              {% if user.is_staff %}
                <li><a href="/admin/">Admin panel</a></li>
              {% endif %}
              <li><a href="/ownexams/">Exams added by you</a></li>
              <li><a href="/account/">Account details</a></li>
              <li><a href="/logout/">Logout</a></li>
            {% else %}
              <li class="nav-header">Login</li>
              <li><a href="/login/">Login form</a></li>
              <li><a href="/register/">Registration</a></li>
            {% endif %}
        </ul>
        {% endblock %}
      </div>
      <div class="span10">
        {% block content %}{% endblock %}
      </div>
    </div>
    <div class="row">
      <div class="span12 well"><a href="https://redmine.tietokilta.fi/projects/tenttiarkisto/issues/">Bug reports & feature requests</a></div>
    </div>
  </div>
</body>
</html>


templates/courselist.html
{% extends "base.html" %}

{% block content %}
<h2>Courses</h2>

{% include "searchform.html" %}

{% if courses %}
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Exams</th>
    </tr>
  </thead>
  {% for course in courses %}
  <tr><td><a href="{{ course.get_absolute_url }}">{{ course.code }}</a></td><td><a href="{{ course.get_absolute_url }}">{{ course.name }}</a></td><td>{{ course.exam_count }}</td></tr>
  {% endfor %}
</table>
{% else %}
<p>No courses match your query! Please search again with a less specific query.</p>
{% endif %}
{% endblock %}

templates/examview.html
{% extends "base.html" %}

{% block content %}
{% if added %}
<div class="alert alert-success">
  The file was succesfully added!
</div>
{% endif %}

<h2>Exam details</h2>
<table class="table table-bordered table-striped">
  <tr>
    <td>Course</td><td><a href="{{ exam.course.get_absolute_url }}">{{ exam.course.code }} {{ exam.course.name }}</a></td>
  </tr>
  <tr>
    <td>Exam date</td><td>{{ exam.exam_date|date:"d.m.Y" }}</td>
  </tr>
  <tr>
    <td>Submitter</td>
    <td>{% if exam.submitter %}
      {{ exam.submitter.username }}
    {% else %}
      Submitter wasn't registered
    {% endif %}</td>
  </tr>
  <tr>
    <td>Added</td><td>{{ exam.date_added }}</td>
  </tr>
</table>
<h2>Exam files</h2>
<table class="table table-bordered table-striped">
  {% for file in files %}
    <tr><td><a href="{{ file.exam_file.url }}">{{ file.exam_file.url }}</a></tr></td>
  {% endfor %}
</table>

<h2>Add file to exam</h2>
<form action="." method="post" enctype="multipart/form-data" class="well">{% csrf_token %}
  {% include "genericform.html" with form=fileform %}
  <input type="submit" value="Add file" class="btn" />
</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
  <h2>Search for courses</h2>
  {% include "partial/searchform.html" %}
  <h2>Archive maintainers</h2>
  <table class="table table-bordered table-striped">
  {% for maintainer in maintainers %}
    <tr><td>{{ maintainer.group }}</td><td>{{ maintainer.view_email }}</td></tr>
  {% endfor %}
  </table>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<h2>Login</h2>

<form class="well" method="post" action="/login/">
{% csrf_token %}
  {% if form.non_field_errors %}
    <div class="alert alert-error">Your username and password didn't match. Please try again.</div>
  {% endif %}
{% include "genericform.html" %}
<input type="submit" value="Login" class="btn" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}


templates/modifyaccount.html
{% extends "base.html" %}

{% block content %}
<h2>Modify account details</h2>
{% if saved %}
<div class="alert alert-success">
  Account details saved successfully!
</div>
{% endif %}
<form class="well" method="post" action=".">
{% csrf_token %}
{% include "genericform.html" %}
<input type="submit" value="Save" class="btn" />
</form>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}
<h2>Account registration</h2>
{% if created %}
  <div class="alert alert-success">
    Account created succesfully! You can now add courses.
  </div>
{% else %}
  <form action="/register/" method="post" class="well">{% csrf_token %}
    {% include "genericform.html" %}
    <input type="submit" value="Register" class="btn" />
  </form>
{% endif %}
{% endblock %}
